- name: iptables persistence packages are installed
  apt:
    name:
      - netfilter-persistent
      - iptables-persistent
    state: present

- name: iptables v4 rules are up
  template:
    src: "{{ iptables_rules_v4 }}"
    dest: /etc/iptables/rules.v4
    mode: "600"
  notify: restart firewall

- name: iptables v6 rules are up
  template:
    src: "{{ iptables_rules_v6 }}"
    dest: /etc/iptables/rules.v6
    mode: "600"
  notify: restart firewall

- name: firewall is activated
  service:
    name: netfilter-persistent
    state: started
    enabled: true
