- hosts: javelin
  become: true

  tasks:
    - import_role:
        name: debian

    - name: basic admin tools are installed
      apt:
        name:
          - curl
          - dnsutils
          - htop
          - net-tools
          - tmux
        state: present

    - name: zfs application-data dataset is present
      zfs:
        name: main/data
        extra_zfs_properties:
          mountpoint: /data
        state: present

    - name: zfs snapshot retention script is up
      copy:
        src: ../assets/snapshot_retention.py
        dest: /usr/local/sbin/snapshot_retention.py
        mode: "755"

    - name: zfs daily snapshot script is up
      copy:
        src: ../assets/zfs_daily_snapshot.sh
        dest: /etc/cron.daily/zfs_daily_snapshot.sh
        mode: "755"
