- hosts: javelin
  become: true

  tasks:
    - import_role:
        name: debian

    - name: basic admin tools are installed
      apt:
        name:
          - dnsutils
          - htop
          - net-tools
          - tmux
        state: present

    - name: zfs application-data dataset is present
      zfs:
        name: main/data
        extra_zfs_properties:
          mountpoint: /data
        state: present
