- name: apt cache is up
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: unattended-upgrades is installed
  apt:
    name: unattended-upgrades
    state: present

- name: unattended-upgrades is activated
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: system reboots after unattended upgrades if needed
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: Unattended-Upgrade::Automatic-Reboot "true";
    state: present

- name: anacron is installed
  apt:
    name: anacron
    state: present
