# This file defines the IP address of the server.

vars:
  host:
    javelin:
      # Public IP address of the server. The output of `terraform output ip`.
      external_address: 0.1.2.3

      # Uncomment this once you successfully configured Wireguard tunnel.
      # ansible_host: "{{ wireguard_address }}"

  group:
    servers:
      ansible_user: admin
      ansible_host: "{{ external_address }}"
